@SmartSprayerAPI_HostAddress = http://localhost:5080

POST {{SmartSprayerAPI_HostAddress}}/sensor-data/

GET {{SmartSprayerAPI_HostAddress}}/sensor-data/

GET {{SmartSprayerAPI_HostAddress}}/sensor-data/device/{deviceId}

GET {{SmartSprayerAPI_HostAddress}}/sensor-data/latest/{deviceId}

PUT {{SmartSprayerAPI_HostAddress}}/sensor-data/{deviceId}

DELETE {{SmartSprayerAPI_HostAddress}}/sensor-data/{deviceId}

GET {{SmartSprayerAPI_HostAddress}}/sensor-data/alerts/{deviceId}

GET {{SmartSprayerAPI_HostAddress}}/health

Accept: application/json

###
